docker:
- image: cimg/node:15.8
steps:
- add_ssh_keys:
    fingerprints:
    - d1:06:ff:c3:58:59:68:6e:a3:2f:69:1d:e2:94:7c:14
- checkout
- run:
    name: Bump dev version
    command: |
      git config --global user.email $GITHUB_USER_EMAIL
      git config --global user.name $GITHUB_USER_NAME
      git checkout dev
      npm run bump-version
      git pull
      git add .
      git commit -m "Bring on version $(node -p "require('./package').version")!"
      git push origin HEAD
