!yamlscript/v0/

docker:
- image: circleci/node:latest

working_directory: ~/calva

steps:
- attach_workspace:
    at: /tmp
- !cmd:
  - Restore build
  - rmdir ~/calva && cp -r /tmp/build ~/calva
- !cmd:
  - Run eslint check
  - npm run eslint
