!yamlscript/v0/

docker:
- image: cibuilds/github:0.10

working_directory: ~/calva

steps:
- !attach-workspace: /tmp

- !cmd:
  - Restore build
  - rmdir ~/calva && cp -r /tmp/build ~/calva

- !bin: Publish Release on GitHub
