docker:
- image: circleci/node:latest
working_directory: ~/calva
steps:
- attach_workspace:
    at: /tmp
- run:
    name: Restore build
    command: rmdir ~/calva && cp -r /tmp/build ~/calva
- run:
    name: Publish to Open VSX
    command: |
      OVSX_CMD="ovsx publish /tmp/artifacts/calva-$(node -p 'require("./package.json").version').vsix --pat ${OVSX_PUBLISH_TOKEN}"
      if [ "${IS_LOCAL}" = YES ]
      then
        echo "Dry npx ${OVSX_CMD}"
      else
        npx ${OVSX_CMD}
      fi
