!yamlscript/v0/

docker:
- image: circleci/node:latest

working_directory: ~/calva

steps:
- !attach-workspace: /tmp

- !cmd:
  - Restore build
  - rmdir ~/calva && cp -r /tmp/build ~/calva

- !cmd:
  - Run prettier format check
  - npm run prettier-check
