docker:
- image: cimg/clojure:1.11-browsers
working_directory: ~/calva
steps:
- attach_workspace:
    at: /tmp
- run:
    name: Restore build
    command: rmdir ~/calva && cp -r /tmp/build ~/calva
- run:
    name: Compile Extension Tests
    command: npm run compile-test
- run:
    name: Apt install missing dependencies
    command: |
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
      sudo apt update && sudo apt install -y libnss3
- run:
    name: Run Extension Tests
    command: npm run integration-test
- store_test_results:
    path: ~/calva/junit
