!yamlscript/v0/

working_directory: ~/calva

environment:
  # Required:
  DISPLAY: :99

docker:
- image: arcanemagus/atom-docker-ci

steps:
- !attach-workspace: /tmp

- !cmd:
  - Restore build
  - rmdir ~/calva && cp -r /tmp/build ~/calva

- run:
    name: Start display server for Atom
    command:
      /sbin/start-stop-daemon --start --quiet
          --pidfile /tmp/custom_xvfb_99.pid
          --make-pidfile --background
          --exec /usr/bin/Xvfb
          --
          :99 -ac -screen 0 1024x768x16 +extension RANDR
    background: true

- !cmd:
  - Run package tests
  - cd src/calva-fmt/atom-language-clojure;
    ./run-grammar-tests.sh

- save_cache:
    name: Save dependencies
    key: ts-{{ checksum "package.json" }}-cljs-{{
               checksum "shadow-cljs.edn" }}-grammar-{{
               checksum "src/calva-fmt/atom-language-clojure/package.json" }}
    paths:
    - ~/.atom/packages
    - ./node_modules
