docker:
- image: cimg/clojure:1.11-browsers
working_directory: ~/calva
steps:
- attach_workspace:
    at: /tmp
- run:
    name: Restore build
    command: rmdir ~/calva && cp -r /tmp/build ~/calva
- run:
    name: Apt install missing dependencies
    command: |
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
      sudo apt update && sudo apt install -y libnss3
- run:
    name: Run VSIX E2E Tests
    command: npm run e2e-test -- --calva-vsix=/tmp/artifacts/calva-$(node -p 'require("./package.json").version').vsix --test-workspace=src/extension-test/e2e-test
- run:
    name: Temporary debug preserving of VS Code network log
    command: for f in /home/circleci/.config/'Code - Insiders'/logs/*/network.log ; do echo "$f"; echo ---; cat "$f"; echo --- ; done
    when: always
- store_test_results:
    path: ~/calva/junit
