!YS-v0:
docker:
  - image: cimg/node:22.16.0

working_directory: ~/calva

steps:
  - !:attach-workspace /tmp

  - !:cmd
    - Restore build
    - rmdir ~/calva && cp -r /tmp/build ~/calva

  - !:cmd
    - Verify CLJS test output after restore
    - ls -l out/cljs-lib/test

  - !:cmd
    - Run CLJS Tests
    - npm run calva-lib-test

  - !:store
    test_results: ~/calva/junit
