!yamlscript/v0/

docker:
- image: circleci/node:latest

working_directory: ~/calva

steps:
- attach_workspace:
    at: /tmp

- !cmd:
  - Restore build
  - rmdir ~/calva && cp -r /tmp/build ~/calva
- !cmd:
  - Run CLJS Tests
  - npm run calva-lib-test
- store_test_results:
    path: ~/calva/junit
